### ISSUE TITLE
[BUG] private repo dependency in a package when upgrading to 16, 18, 20 (probably 22 not attempted) gives no information as to the failure

### ISSUE THREAD

**Issue by nicktackes** [npm/metavuln-calculator#150]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Sorry, but im not sure where to even attempt to find the source of this problem and hoping you can provide some insight.  Before node 16, running an npm install with a package containing my private repo successfully completes, generates package lock and loads node modules, however starting with node 16, i ge4t this output when running verbose.... can i somehow get anything meaningful regarding what is going on with metavuln in this situation?

9088 verbose unfinished npm timer auditReport:init 1726155021548
9089 verbose unfinished npm timer metavuln:calculate:security-advisory:@molecularmatch/mm-domains:pDx2xtbBERWTaSRbvJA+n9V8HlVlhsdAgOynO/iM7q6/1l6WoIVUTgi4Rbp5vltVmomFYigLbL0Pvf/0PYWvyQ== 1726155023802
9090 verbose unfinished npm timer metavuln:load:security-advisory:@molecularmatch/mm-domains:pDx2xtbBERWTaSRbvJA+n9V8HlVlhsdAgOynO/iM7q6/1l6WoIVUTgi4Rbp5vltVmomFYigLbL0Pvf/0PYWvyQ== 1726155023824
9091 verbose code 1

### Steps To Reproduce

1. In this environment...
2. With this config...
3. Run '...'
4. See error...

### Environment

- npm:8.19.4
- Node:v16.20.2
- OS:mac Sonoma 14.4.1
- platform: apple m1 pro - macbook pro

**Comment by nicktackes** [comment]
npm verb stack Error: loading from incorrect packument
npm verb stack     at Advisory.load (/Users/nicktackes/.nvm/versions/node/v16.20.2/lib/node_modules/npm/node_modules/@npmcli/metavuln-calculator/lib/advisory.js:91:27)
npm verb stack     at Calculator.[calculate] (/Users/nicktackes/.nvm/versions/node/v16.20.2/lib/node_modules/npm/node_modules/@npmcli/metavuln-calculator/lib/index.js:60:14)
npm verb stack     at async Promise.all (index 0)
npm verb stack     at async Map.[init] (/Users/nicktackes/.nvm/versions/node/v16.20.2/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/audit-report.js:188:9)
npm verb stack     at async Map.run (/Users/nicktackes/.nvm/versions/node/v16.20.2/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/audit-report.js:109:7)
npm verb cwd /Users/nicktackes/WebstormProjects/mm
