### ISSUE TITLE
[BUG] v1.1.1: TypeError: semver.simplifyRange is not a function

### ISSUE THREAD

**Issue by sbourlon** [npm/metavuln-calculator#9]
# What / Why
Hello npm team,

Maybe there is a bug in metavuln-calculator v1.1.1 according to the logs from npm:

```
4500 verbose stack TypeError: semver.simplifyRange is not a function
4500 verbose stack     at Advisory.[calculateRange] (/usr/lib/node_modules/npm/node_modules/@npmcli/metavuln-calculator/lib/advisory.js:191:16)
4500 verbose stack     at Advisory.load (/usr/lib/node_modules/npm/node_modules/@npmcli/metavuln-calculator/lib/advisory.js:148:28)
4500 verbose stack     at Calculator.[calculate] (/usr/lib/node_modules/npm/node_modules/@npmcli/metavuln-calculator/lib/index.js:59:14)
4500 verbose stack     at async Promise.all (index 39)
4500 verbose stack     at async Map.[init] (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/audit-report.js:178:7)
4500 verbose stack     at async Map.run (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/audit-report.js:106:7)
4501 verbose cwd /home/user/Documents/src/git/github.com/6prod/website
4502 verbose Linux 5.12.1-arch1-1
4503 verbose argv "/usr/bin/node" "/usr/bin/npm" "install"
4504 verbose node v16.1.0
4505 verbose npm  v7.13.0
4506 error semver.simplifyRange is not a function
4507 verbose exit 1
```

The version of metavuln-calculator on my system is 1.1.1 according to its package.json.

## When
Whenever I run `npm install`

## Where
  * npm public registry

## How
I am trying to upgrade my nextjs project.

It tried different fix:
- npm upgrade / npm install
- rm -rf node_modules && npm install
- rm -rf ~/.npm && npm cache clean --force && rm -rf node_modules && npm install

### Current Behavior
```
% npm install            
npm ERR! semver.simplifyRange is not a function

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2021-05-18T02_16_10_879Z-debug.log
```

with /home/user/.npm/_logs/2021-05-18T02_16_10_879Z-debug.log ending with:
```
277 timing metavuln:cache:get:security-advisory:postcss-selector-matches:GBiyG6xpo+KckWadrabw1lxbPmjLCzFcARvKCaNwRXmHkG+66Znn2nDvm+xoQapzPs9gsFjMsuB/lBpZm62tFQ== Completed in 30ms
278 timing metavuln:cache:get:security-advisory:postcss-selector-not:vCEfw5YBLPriFqX9QPA6DTvKqM7npXQDO/F/q4JHefVN58FlKTdc5QN79724IyuPsyByAvDiU2VcVYjqqwHwVw== Completed in 30ms
279 timing metavuln:cache:get:security-advisory:sanitize-html:fMZM9Bt4doYYI0BO0W0NhVaPgoOW5L6QUULL1tS2wgS0QQiQiaxpErLMiaYcFBDnEBrhBvOxQMpRfM7eKskxuQ== Completed in 29ms
280 verbose stack TypeError: semver.simplifyRange is not a function
280 verbose stack     at Advisory.[calculateRange] (/usr/lib/node_modules/npm/node_modules/@npmcli/metavuln-calculator/lib/advisory.js:191:16)
280 verbose stack     at Advisory.load (/usr/lib/node_modules/npm/node_modules/@npmcli/metavuln-calculator/lib/advisory.js:148:28)
280 verbose stack     at Calculator.[calculate] (/usr/lib/node_modules/npm/node_modules/@npmcli/metavuln-calculator/lib/index.js:59:14)
280 verbose stack     at async Promise.all (index 39)
280 verbose stack     at async Map.[init] (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/audit-report.js:178:7)
280 verbose stack     at async Map.run (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/audit-report.js:106:7)
281 verbose cwd /home/user/Documents/src/git/github.com/6prod/website
282 verbose Linux 5.12.1-arch1-1
283 verbose argv "/usr/bin/node" "/usr/bin/npm" "install"
284 verbose node v16.1.0
285 verbose npm  v7.13.0
286 error semver.simplifyRange is not a function
287 verbose exit 1
```

Gist of the full debug file: https://gist.github.com/sbourlon/4ed004b59db36851ed55bbf08deb906c

### Steps to Reproduce
Versions used:
- npm:
```
% pacman -Qi npm
Name            : npm
Version         : 7.13.0-1
Description     : A package manager for javascript
```
- semver:
```
% pacman -Qi semver
Name            : semver
Version         : 7.3.5-2
Description     : The semantic version parser used by npm
Architecture    : any
URL             : https://github.com/npm/node-semver
```

Reproduce:
- npm install

### Expected Behavior
npm install sucessfully finish.

## Who
@npm

**Comment by sbourlon** [comment]
A quick and dirty temporary workaround is to used an older version of npm/semver:
```
sudo npm install -g npm@7.7.0
sudo npm install -g semver@7.2.0
```

**Comment by wraithgar** [comment]
This has been fixed.  the cli semver is set to a version of semver that includes this function.
